[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.112.2"
uvicorn = {extras = ["standart"], version = "^0.30.6"}
pydantic-settings = "^2.4.0"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"